name: Build xwarp with gradle

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with gradle wrapper
      uses: ./gradlew build
